### ISSUE TITLE
Fix `Runtime Compiler is not loaded` when building with AoT on the example code

### ISSUE THREAD

**Issue by JLHwung** [DenysVuika/developing-with-angular#38]
The [example code](https://github.com/DenisVuyka/developing-with-angular/blob/master/angular/plugins/src/app/sidebar/sidebar.component.ts) will throw `Runtime Compiler is not loaded` when compiled with Ahead-of-Time Angular Compiler (see https://github.com/angular/angular/issues/12885).

Switching to JIT mode might mitigate this error but JIT mode is less performant and thus is not recommended for production environment. As the plugin is lazily loaded and not precompiled, we should manually use `JitCompilerFactory` to create a jit compiler. The example is [here](https://github.com/angular/angular/blob/d7a727cc0728a61a707f2c109636c1fa077042c2/integration/dynamic-compiler/src/app.module.ts#L16) for the reference.

**Comment by DenisVuyka** [comment]
That’s a very good point, thanks for sharing. I will try to adopt examples for AoT.

**Comment by sirockin** [comment]
@JLHwung I tried integrating the example code into an Angular 6 project I made based on @DenisVuyka's [Medium article(https://medium.com/@DenysVuika/dynamic-content-in-angular-2-3c85023d9c36) but get the following error when I run in production mode:
```
main.5a839a64bd38007b2b87.js:1 ERROR Error: No NgModule metadata found for 'function(){}'.
    at t.resolve (main.5a839a64bd38007b2b87.js:1)
    at t.getNgModuleMetadata (main.5a839a64bd38007b2b87.js:1)
    at t._loadModules (main.5a839a64bd38007b2b87.js:1)
    at t._compileModuleAndAllComponents (main.5a839a64bd38007b2b87.js:1)
    at t.compileModuleAndAllComponentsSync (main.5a839a64bd38007b2b87.js:1)
```
The code works fine in development mode.

Thanks in advance for any feedback.

**Comment by JLHwung** [comment]
@sirockin 
Hi Dave, the error is due to dynamic module is not AoT-compiled. Have you checked https://github.com/angular/angular/blob/d7a727cc0728a61a707f2c109636c1fa077042c2/integration/dynamic-compiler/src/app.module.ts#L16 to provider a compiler on production mode?

**Comment by sirockin** [comment]
Yes - I copied the example you gave there exactly and integrated it into my own code - that's what is raising the error.

**Comment by sirockin** [comment]
@JLHwung I'm sorry the terminology you've used is outside my expertise at the moment. 

I've simply:
1. generated a standard project using the angular 6 CLI
2. Incorporated the code from @DenisVuyka 's example above - this works in development but not production mode
3. Tried to fix the production bug by incorporate the code you supplied above

I can't find the terms `rollup` or `ngc` anywhere in my project source.  I know this may be outside of the scope of this issue but please could you give me a clue as to where I could look to understand this better?

**Comment by JLHwung** [comment]
@sirockin If I am not misunderstanding, things you have done is:

- Use Angular 6 CLI to setup your project
- Incorporate Denis Vukya's example and Custom Compiler settings.

The key point is that, if you would like to dynamically load `NgModule` (what I mean dynamic is that you can specify the module name in the runtime and compile the module on-the-fly), then the loaded angular module, written in TypeScript, must have been bundled _in some way_ outside your main project.

In this [example](https://github.com/DenisVuyka/developing-with-angular/blob/master/angular/plugins/src/app/sidebar/sidebar.component.ts), the question is, how do you bundle the `sidebar` component? You can see in this [example](https://github.com/DenisVuyka/developing-with-angular/blob/master/angular/plugins-example/rollup.config.js) that the `plugin` is bundled by rollup.

**Comment by sirockin** [comment]
Thank you @JLHwung . I will need to read these examples carefully to get a better understanding and then get back to you.

**Comment by DenisVuyka** [comment]
You can also use this article for some ideas on how to avoid using compiler entirely: https://medium.com/@DenysVuika/dynamic-material-sidebar-in-angular-fe7013dabf5c.

**Comment by sirockin** [comment]
Thanks @DenisVuyka. The bit I'm interested in is dynamically compiling content templates on the fly (for an application where users can upload their own content templates). I got that working using [your article here](https://medium.com/@DenysVuika/dynamic-content-in-angular-2-3c85023d9c36) but it didn't work in production. I think it's time for me to buy your book and have a deep dive into the advanced section. :-)

**Comment by DenysVuika** [comment]
I suggest also checking this blog post for more ideas: https://blog.angularindepth.com/here-is-what-you-need-to-know-about-dynamic-components-in-angular-ac1e96167f9e

**Comment by praveenkumar-r** [comment]
> The [example code](https://github.com/DenisVuyka/developing-with-angular/blob/master/angular/plugins/src/app/sidebar/sidebar.component.ts) will throw `Runtime Compiler is not loaded` when compiled with Ahead-of-Time Angular Compiler (see [angular/angular#12885](https://github.com/angular/angular/issues/12885)).
> 
> Switching to JIT mode might mitigate this error but JIT mode is less performant and thus is not recommended for production environment. As the plugin is lazily loaded and not precompiled, we should manually use `JitCompilerFactory` to create a jit compiler. The example is [here](https://github.com/angular/angular/blob/d7a727cc0728a61a707f2c109636c1fa077042c2/integration/dynamic-compiler/src/app.module.ts#L16) for the reference.

**Comment by praveenkumar-r** [comment]
> The [example code](https://github.com/DenisVuyka/developing-with-angular/blob/master/angular/plugins/src/app/sidebar/sidebar.component.ts) will throw `Runtime Compiler is not loaded` when compiled with Ahead-of-Time Angular Compiler (see [angular/angular#12885](https://github.com/angular/angular/issues/12885)).
> 
> Switching to JIT mode might mitigate this error but JIT mode is less performant and thus is not recommended for production environment. As the plugin is lazily loaded and not precompiled, we should manually use `JitCompilerFactory` to create a jit compiler. The example is [here](https://github.com/angular/angular/blob/d7a727cc0728a61a707f2c109636c1fa077042c2/integration/dynamic-compiler/src/app.module.ts#L16) for the reference.

This worked like a charm. Thanks for sharing the example.

**Comment by praveenkumar-r** [comment]
@JLHwung The example which you shared worked like a charm. Thanks a lot
