### ISSUE TITLE
Issue with DI in plugins (StaticInjectorError: NullInjectorError: No provider for HttpHandler)

### ISSUE THREAD

**Issue by retmas-dv** [DenysVuika/developing-with-angular#42]
Hi Denys,
thank you for very impressive chapter "Plugins" of your amazing book.

I am sorry to bother you but I found an issue with DI and dynamically loaded components (from external plugin). If HttpClient is used in my-label component then "StaticInjectorError: NullInjectorError: No provider for HttpHandler" exception occurs while createComponent (the log attached).

I've uploaded the source to reproduce this issue.
https://github.com/retmas-dv/developing-with-angular/blob/master/angular/plugins-example/src/my-label/my-label.component.ts
https://github.com/retmas-dv/developing-with-angular/blob/master/angular/plugins/src/app/app.component.ts

Could you please take a look if you have a time? Any ideas to resolve this will really help.

<img width="582" alt="no_provider_problem" src="https://user-images.githubusercontent.com/5990165/43680762-3b56cdc4-984a-11e8-8a9d-6c410706cbd2.png">

[no_provider_problem_localhost-1530694362721.log](https://github.com/DenisVuyka/developing-with-angular/files/2259840/no_provider_problem_localhost-1530694362721.log)

**Comment by DenisVuyka** [comment]
thanks, I will try to reproduce. meanwhile you can use a workaround with providing any service at runtime:

![image](https://user-images.githubusercontent.com/503991/43683737-9727ff30-9889-11e8-8a75-01b6e30732dd.png)

For example, instead of messing with the module configurations and dependencies, you can just give your plugin an object with resolved services. You can also set any instance property and call any method.

**Comment by retmas-dv** [comment]
Thanks, I use this approach right now. But it's interesting why DI does not work correctly in this case.

**Comment by DenisVuyka** [comment]
Needs to be investigated. Probably some configuration needed, like adding "HttpClientModule" to the `exports` section, or adding Http client to the injector.

**Comment by retmas-dv** [comment]
I have tried to add HttpClientModule to the exports:
`const DynamicModule = NgModule({
                imports: [CommonModule],
                providers: [],
                declarations: [componentType],
                exports: [HttpClientModule]
            })(class { });`
but no effect.

**Comment by retmas-dv** [comment]
if I add HttpClient into provides then exception "NullInjectorError: No provider for HttpHandler!"

**Comment by DenysVuika** [comment]
I suggest also checking this blog post for more ideas: https://blog.angularindepth.com/here-is-what-you-need-to-know-about-dynamic-components-in-angular-ac1e96167f9e
