### ISSUE TITLE
unpkg error when starting plugins code

### ISSUE THREAD

**Issue by bdbrandt** [DenysVuika/developing-with-angular#47]
Hi Denys,

Thank you for the amazing chapter on plugins in your book!

I'm having trouble getting the sample code working in that chapter. When running the application through `npm start` after completing the step at the top of page 374, I am getting a unpkg.com/internal@1.0.8/Observable:1 GET https://unpkg.com/internal@1.0.8/Observable 404 error in my console. I am have tried using the code directly from this repository (and running all the necessary npm installs and npm links) and have the same error. Attached is the error log from my console. Any ideas how to fix this?

Thank you!
Ben
[localhost-1558540606994.log](https://github.com/DenysVuika/developing-with-angular/files/3208301/localhost-1558540606994.log)

**Comment by ganeshmaa** [comment]
Any update on this ?Did u solve this error?

**Comment by DenysVuika** [comment]
Something might have changed at the unpkg side, I will check the code.

**Comment by DenysVuika** [comment]
All examples updated to Angular 8, should work now.
