### ISSUE TITLE
Angular 8 Version

### ISSUE THREAD

**Issue by ganeshmaa** [DenysVuika/developing-with-angular#49]
Hi Denys ,we are looking for Plugin Architecture in our projects and May i know when will we get the angular 8 Update

**Comment by DenysVuika** [comment]
At this point I am not planning to update examples to Angular 8. The Ivy is not ready yet and there are issues with the v8, probably will skip to v9. You can try upgrading yourself, they got the guide here: https://update.angular.io/

**Comment by DenysVuika** [comment]
All examples updated to Angular 8
